# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Official Dime.Scheduler CLI"
  homepage "https://github.com/dime-scheduler/distro"
  version "0.8.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.8.0/dimescheduler_0.8.0_darwin_x86_64.tar.gz"
      sha256 "fceac27372be161ca69ee91f2e33d3806e0959423c6b21b6c38a991e3099de04"

      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
    if Hardware::CPU.arm?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.8.0/dimescheduler_0.8.0_darwin_arm64.tar.gz"
      sha256 "a56a1adfbf9af0643660790c13c70f3b8233839294acf4d56685e83ab344adc4"

      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.8.0/dimescheduler_0.8.0_linux_x86_64.tar.gz"
      sha256 "900c1458aef1c584515812bf0ce51343219d40bc4018ca8ed15066e87e0287e1"
      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.8.0/dimescheduler_0.8.0_linux_arm64.tar.gz"
      sha256 "ee93e497cafc793144ce050018e41f654a9ab2415b6a026dedb3113b53659c99"
      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
  end

  test do
    system "#{bin}/dimescheduler version"
  end
end
