# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Official Dime.Scheduler CLI"
  homepage "https://github.com/dime-scheduler/distro"
  version "0.11.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.11.0/dimescheduler_0.11.0_darwin_x86_64.tar.gz"
      sha256 "cb1ea876f5b53c532677fb85f1afc34978c1c8eb6db81337218b29f4509ee311"

      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
    if Hardware::CPU.arm?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.11.0/dimescheduler_0.11.0_darwin_arm64.tar.gz"
      sha256 "f790e661a2fd25c7644d2da2755ceae26020c73cf9af3e89b64e4932667dcaae"

      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.11.0/dimescheduler_0.11.0_linux_x86_64.tar.gz"
      sha256 "51e17f1d8e0c9a8de19851003e46ac6005cc4c152e8bab8c310b14f632341fd9"
      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.11.0/dimescheduler_0.11.0_linux_arm64.tar.gz"
      sha256 "8b0e54a69f6b26b70042ac2ecf4a3583998087bd5d89042d7e72bae09aaf808f"
      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
  end

  test do
    system "#{bin}/dimescheduler version"
  end
end
