# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dimescheduler < Formula
  desc "Official Dime.Scheduler CLI"
  homepage "https://github.com/dime-scheduler/distro"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.1.0/dimescheduler_0.1.0_darwin_x86_64.tar.gz"
      sha256 "371f463f96975ede368a38ee3adf629a3176a98a1e60d1284cbf7f76cdd4e04c"

      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
    if Hardware::CPU.arm?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.1.0/dimescheduler_0.1.0_darwin_arm64.tar.gz"
      sha256 "04047c504ef1ef228abf7fda884bc2358f90c16e2c553a0ea1c3c8d8ff1991ac"

      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.1.0/dimescheduler_0.1.0_linux_x86_64.tar.gz"
      sha256 "44ea83f0de3b6eb5776cf83161bf85509bbbd7394625ee12dfcb27e5cfab3343"
      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.1.0/dimescheduler_0.1.0_linux_arm64.tar.gz"
      sha256 "e0a5262ecf2b99695d41b6ca3506f03c9fefae13814ef92a3ea444d85880811c"
      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
  end

  test do
    system "#{bin}/dimescheduler version"
  end
end
