# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dimescheduler < Formula
  desc "Official Dime.Scheduler CLI"
  homepage "https://github.com/dime-scheduler/distro"
  version "0.3.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.3.0/dimescheduler_0.3.0_darwin_x86_64.tar.gz"
      sha256 "a19e98377df45afaf30f20e4351c85f414b9a03987cc4703d6d27a334fd1f07e"

      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
    if Hardware::CPU.arm?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.3.0/dimescheduler_0.3.0_darwin_arm64.tar.gz"
      sha256 "fc801621e76ebdc8f07e8245babe446d91296ae5aec66f26a5e0ffa88c212e1e"

      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.3.0/dimescheduler_0.3.0_linux_x86_64.tar.gz"
      sha256 "eb5fc7d16508a257dcd0d0f0d85dbca93fb6ead7d8811e6a93eac565d018e9c2"
      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://stdimescheduler.blob.core.windows.net/cli/v0.3.0/dimescheduler_0.3.0_linux_arm64.tar.gz"
      sha256 "19ff15e979424384a02683bb857eb94e2160067c95bad553873fd05107351a1a"
      define_method(:install) do
        bin.install "dimescheduler"
      end
    end
  end

  test do
    system "#{bin}/dimescheduler version"
  end
end
